# Generated by Django 5.1.5 on 2025-03-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Active'), (2, 'Inactive'), ('Sold', 3)], default=1),
        ),
    ]
