# Generated by Django 5.1.5 on 2025-03-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_brand_region_rename_is_main_category_for_footer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='for_footer',
            new_name='is_main',
        ),
        migrations.RemoveField(
            model_name='category',
            name='for_header',
        ),
        migrations.RemoveField(
            model_name='category',
            name='for_mid_part',
        ),
        migrations.RemoveField(
            model_name='category',
            name='is_option',
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(),
        ),
    ]
